function MOD = setMOSFETParms(inMOD, Type)
% function MOD = setMOSFETParms(inMOD, Type)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Setting parameters for MOSFETs is not so convenient in MAPP (especially if
% you just want a default set of paramters to be set for you model). This
% scripts automates that process (and conveniently lets you set different and
% appropriate paramters for NMOS and PMOS so that you don't have to type it
% in again and again)
%
% INPUTS:
%     inMOD: Input ModSpec model
%     Type: Specify whether the output model should be an 'MVS_NMOS' or a 
%         'MVS_PMOS'. Also supported: BSIM_NMOS, BSIM_PMOS, 'VA_BSIM_PMOS' and
%         'VA_BSIM_NMOS'
% 
% OUTPUTS:
%     MOD: Output ModSpec model with the appropriately set of parameters set!
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Author:   Archit Gupta 
% Date:     March 23, 2016
% Update:   January 19, 2018 (Reduced the number of parameters and models for
%           the device-models package)
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    MOD = inMOD;    % Copy everything, just need to reset the parameter values

    if (nargin < 2)
        Type = 'NMOS';
    end

    switch Type
        case 'SH_NMOS'
            parm_names = { ...
                'Type' ...
            };
            parm_vals = { ...
                'N' ...
            };
        case 'SH_PMOS'
            parm_names = { ...
                'Type' ...
            };
            parm_vals = { ...
                'P' ...
            };
        case 'VA_PSP103_NMOS'
            parm_names = { ...
                'parm_TYPE' ...
            };
            parm_vals = { ...
                1 ...
            };
        case 'VA_PSP103_PMOS'
            parm_names = { ...
                'parm_TYPE' ...
            };
            parm_vals = { ...
                -1 ...
            };
        case 'VA_MVS101_PMOS'
            parm_names = { ...
                'parm_type'    , ...
                'parm_W'       , ...
                'parm_Lgdr'    , ...
                'parm_dLg'     , ...
                'parm_Cg'      , ...
                'parm_beta'    , ...
                'parm_alpha'   , ...
                'parm_Cif'     , ...
                'parm_Cof'     , ...
                'parm_phib'    , ...
                'parm_gamma'   , ...
                'parm_mc'      , ...
                'parm_CTM_select', ...
                'parm_Rs0'     , ...
                'parm_Rd0'     , ...
                'parm_n0'      , ...
                'parm_nd'      , ...
                'parm_vxo'     , ...
                'parm_mu'      , ...
                'parm_Vt0'     , ...
                'parm_delta'     ... 
            };
            parm_vals = { ...
                -1, ...
                1.0e-4, ...
                32e-7, ...
                8e-7, ...
                2.57e-6, ...
                1.8, ...
                3.5, ...
                1.38e-12, ...
                1.47e-12, ...
                1.2, ...
                0.1, ...
                0.2, ...
                1, ...
                100, ...
                100, ...
                1.68, ...
                0.1, ...
                7542204, ...
                165, ...
                0.5535, ...
                0.15
            };
        case 'VA_MVS101_NMOS'
            parm_names = { ...
                'parm_type'    , ...
                'parm_W'       , ...
                'parm_Lgdr'    , ...
                'parm_dLg'     , ...
                'parm_Cg'      , ...
                'parm_beta'    , ...
                'parm_alpha'   , ...
                'parm_Cif'     , ...
                'parm_Cof'     , ...
                'parm_phib'    , ...
                'parm_gamma'   , ...
                'parm_mc'      , ...
                'parm_CTM_select', ...
                'parm_Rs0'     , ...
                'parm_Rd0'     , ...
                'parm_n0'      , ...
                'parm_nd'      , ...
                'parm_vxo'     , ...
                'parm_mu'      , ...
                'parm_Vt0'     , ...
                'parm_delta'     ... 
            };
            parm_vals = { ...
                1, ...
                1.0e-4, ...
                32e-7, ...
                9e-7, ...
                2.57e-6, ...
                1.8, ...
                3.5, ...
                1.38e-12, ...
                1.47e-12, ...
                1.2, ...
                0.1, ...
                0.2, ...
                1, ...
                100, ...
                100, ...
                1.68, ...
                0.1, ...
                1.2e7, ...
                200, ...
                0.4, ...
                0.15};
        case 'VA_BSIM3_PMOS'
            parm_names = { ...
                'parm_Type',    ...
                'parm_w',       ...
                'parm_tnom',    ...
                'parm_nch',     ...
                'parm_k2',      ...
                'parm_w0',      ...
                'parm_dvt1w',   ...
                'parm_dvt0',    ...
                'parm_u0',      ...
                'parm_uc',      ...
                'parm_ags',     ...
                'parm_keta',    ...
                'parm_rdsw',    ...
                'parm_wr',      ...
                'parm_dwg',     ...
                'parm_dwb',     ...
                'parm_cit',     ...
                'parm_cdscb',   ...
                'parm_dsub',    ...
                'parm_pdiblc2', ...
                'parm_pscbe1',  ...
                'parm_delta',   ...
                'parm_prt',     ...
                'parm_kt1l',    ...
                'parm_ub1',     ...
                'parm_wl',      ...
                'parm_wwn',     ...
                'parm_lln',     ...
                'parm_lwl',     ...
                'parm_cgdo',    ...
                'parm_cj',      ...
                'parm_cjsw',    ...
                'parm_cjswg',   ...
                'parm_cf',      ...
                'parm_pk2',     ...
                'parm_pu0',     ...
                'parm_pvsat',   ...
                'parm_l',       ...
                'parm_tox',     ...
                'parm_vth0',    ...
                'parm_k3',      ...
                'parm_nlx',     ...
                'parm_dvt2w',   ...
                'parm_dvt1',    ...
                'parm_ua',      ...
                'parm_vsat',    ...
                'parm_b0',      ...
                'parm_a1',      ...
                'parm_prwg',    ...
                'parm_wint',    ...
                'parm_voff',    ...
                'parm_cdsc',    ...
                'parm_eta0',    ...
                'parm_pclm',    ...
                'parm_pdiblcb', ...
                'parm_pscbe2',  ...
                'parm_rsh',     ...
                'parm_ute',     ...
                'parm_kt2',     ...
                'parm_uc1',     ...
                'parm_wln',     ...
                'parm_wwl',     ...
                'parm_lw',      ...
                'parm_capmod',  ...
                'parm_cgso',    ...
                'parm_pb',      ...
                'parm_pbsw',    ...
                'parm_pbswg',   ...
                'parm_pvth0',   ...
                'parm_wketa',   ...
                'parm_pua',     ...
                'parm_peta0',   ...
                'parm_toxm',    ...
                'parm_xj',      ...
                'parm_k1',      ...
                'parm_k3b',     ...
                'parm_dvt0w',   ...
                'parm_dvt2',    ...
                'parm_ub',      ...
                'parm_a0',      ...
                'parm_b1',      ...
                'parm_a2',      ...
                'parm_prwb',    ...
                'parm_lint',    ...
                'parm_nfactor', ...
                'parm_cdscd',   ...
                'parm_etab',    ...
                'parm_pdiblc1', ...
                'parm_drout',   ...
                'parm_pvag',    ...
                'parm_mobmod',  ...
                'parm_kt1',     ...
                'parm_ua1',     ...
                'parm_at',      ...
                'parm_ww',      ...
                'parm_ll',      ...
                'parm_lwn',     ...
                'parm_xpart',   ...
                'parm_cgbo',    ...
                'parm_mj',      ...
                'parm_mjsw',    ...
                'parm_mjswg',   ...
                'parm_prdsw',   ...
                'parm_lketa',   ...
                'parm_pub',     ...
                'parm_pketa'    ...
            };
            parm_vals = { ...
                -1,           ... % Type
                0.540001e-6,  ... % w
                27,           ... % tnom
                4.1589e17,    ... % nch
                0.0258663,    ... % k2
                1e-6,         ... % w0
                0,            ... % dvt1w
                0.6117215,    ... % dvt0
                106.5280265,  ... % u0
                -1e-10,       ... % uc
                0.3667554,    ... % ags
                0.0237092,    ... % keta
                304.9893888,  ... % rdsw
                1,            ... % wr
                -2.44019e-8,  ... % dwg
                -9.06003e-10, ... % dwb
                0,            ... % cit
                0,            ... % cdscb
                1.0998181,    ... % dsub
                0.0420477,    ... % pdiblc2
                1.073111e10,  ... % pscbe1
                0.01,         ... % delta
                0,            ... % prt
                0,            ... % kt1l
                -7.61e-18,    ... % ub1
                0,            ... % wl
                1,            ... % wwn
                1,            ... % lln
                0,            ... % lwl
                6.41e-10,     ... % cgdo
                1.200422e-3,  ... % cj
                2.001802e-10, ... % cjsw
                4.22e-10,     ... % cjswg
                0,            ... % cf
                1.799383e-3,  ... % pk2
                -1.3399122,   ... % pu0
                -50,          ... % pvsat
                0.18e-6,      ... % l
                4.1e-9,       ... % tox
                -0.3835898,   ... % vth0
                0,            ... % k3
                1.20187e-7,   ... % nlx
                0,            ... % dvt2w
                0.2286816,    ... % dvt1
                1.125454e-9,  ... % ua
                1.593712e5,   ... % vsat
                5.263128e-7,  ... % b0
                0.2276342,    ... % a1
                0.5,          ... % prwg
                0,            ... % wint
                -0.0878287,   ... % voff
                2.4e-4,       ... % cdsc
                0.1672562,    ... % eta0
                2.2249148,    ... % pclm
                -1e-3,        ... % pdiblcb
                3.099395e-9,  ... % pscbe2
                7.4,          ... % rsh
                -1.5,         ... % ute
                0.022,        ... % kt2
                -5.6e-11,     ... % uc1
                1,            ... % wln
                0,            ... % wwl
                0,            ... % lw
                2,            ... % capmod
                6.41e-10,     ... % cgso
                0.8478616,    ... % pb
                0.8483594,    ... % pbsw
                0.8483594,    ... % pbswg
                2.098588e-3,  ... % pvth0
                0.0295614,    ... % wketa
                -5.27759e-11, ... % pua
                1.003159e-4,  ... % peta0
                4.1e-9,       ... % toxm
                1e-7,         ... % xj
                0.59111,      ... % k1
                7.9143108,    ... % k3b
                0,            ... % dvt0w
                0.1,          ... % dvt2
                1e-21,        ... % ub
                1.6904754,    ... % a0
                1.496707e-6,  ... % b1
                0.6915706,    ... % a2
                0.2553725,    ... % prwb
                3.217673e-8,  ... % lint
                1.8560303,    ... % nfactor
                0,            ... % cdscd
                -0.1249603,   ... % etab
                8.275696e-4,  ... % pdiblc1
                0,            ... % drout
                15,           ... % pvag
                1,            ... % mobmod
                -0.11,        ... % kt1
                4.31e-9,      ... % ua1
                3.3e4,        ... % at
                0,            ... % ww
                0,            ... % ll
                1,            ... % lwn
                0.5,          ... % xpart
                1e-12,        ... % cgbo
                0.4105254,    ... % mj
                0.3400571,    ... % mjsw
                0.3400571,    ... % mjswg
                4.4771801,    ... % prdsw
                -1.935751e-3, ... % lketa
                1e-21,        ... % pub
                -3.434535e-3  ... % pketa
            };
        case 'VA_BSIM3_NMOS'
            parm_names = { ...
                'parm_Type',    ...
                'parm_w',       ...
                'parm_l',       ...
                'parm_toxm',    ...
                'parm_tnom',    ...
                'parm_xj',      ...
                'parm_k1',      ...
                'parm_k3b',     ...
                'parm_dvt0w',   ...
                'parm_dvt0',    ...
                'parm_u0',      ...
                'parm_uc',      ...
                'parm_ags',     ...
                'parm_keta',    ...
                'parm_rdsw',    ...
                'parm_wr',      ...
                'parm_dwg',     ...
                'parm_dwb',     ...
                'parm_cit',     ...
                'parm_cdscb',   ...
                'parm_dsub',    ...
                'parm_pdiblc2', ...
                'parm_pscbe1',  ...
                'parm_delta',   ...
                'parm_prt',     ...
                'parm_kt1l',    ...
                'parm_ub1',     ...
                'parm_wl',      ...
                'parm_wwn',     ...
                'parm_lln',     ...
                'parm_lwl',     ...
                'parm_cgdo',    ...
                'parm_cj',      ...
                'parm_cjsw',    ...
                'parm_cjswg',   ...
                'parm_cf',      ...
                'parm_pk2',     ...
                'parm_pu0',     ...
                'parm_pvsat',   ...
                'parm_tox',     ...
                'parm_nch',     ...
                'parm_k2',      ...
                'parm_w0',      ...
                'parm_dvt1w',   ...
                'parm_dvt1',    ...
                'parm_ua',      ...
                'parm_vsat',    ...
                'parm_b0',      ...
                'parm_a1',      ...
                'parm_prwg',    ...
                'parm_wint',    ...
                'parm_voff',    ...
                'parm_cdsc',    ...
                'parm_eta0',    ...
                'parm_pclm',    ...
                'parm_pdiblcb', ...
                'parm_pscbe2',  ...
                'parm_rsh',     ...
                'parm_ute',     ...
                'parm_kt2',     ...
                'parm_uc1',     ...
                'parm_wln',     ...
                'parm_wwl',     ...
                'parm_lw',      ...
                'parm_capmod',  ...
                'parm_cgso',    ...
                'parm_pb',      ...
                'parm_pbsw',    ...
                'parm_pbswg',   ...
                'parm_pvth0',   ...
                'parm_wketa',   ...
                'parm_pua',     ...
                'parm_peta0',   ...
                'parm_vth0',    ...
                'parm_k3',      ...
                'parm_nlx',     ...
                'parm_dvt2w',   ...
                'parm_dvt2',    ...
                'parm_ub',      ...
                'parm_a0',      ...
                'parm_b1',      ...
                'parm_a2',      ...
                'parm_prwb',    ...
                'parm_lint',    ...
                'parm_nfactor', ...
                'parm_cdscd',   ...
                'parm_etab',    ...
                'parm_pdiblc1', ...
                'parm_drout',   ...
                'parm_pvag',    ...
                'parm_mobmod',  ...
                'parm_kt1',     ...
                'parm_ua1',     ...
                'parm_at',      ...
                'parm_ww',      ...
                'parm_ll',      ...
                'parm_lwn',     ...
                'parm_xpart',   ...
                'parm_cgbo',    ...
                'parm_mj',      ...
                'parm_mjsw',    ...
                'parm_mjswg',   ...
                'parm_prdsw',   ...
                'parm_lketa',   ...
                'parm_pub',     ...
                'parm_pketa'    ...
            };
            parm_vals = { ...
                1,            ... % Type
                0.54e-5,      ... % w
                0.18e-6,      ... % l
                5.1e-9,       ... % toxm
                27,           ... % tnom
                1e-7,         ... % xj
                0.6064385,    ... % k1
                2.763267,     ... % k3b
                0,            ... % dvt0w
                1.3330881,    ... % dvt0
                258.9066683,  ... % u0
                5.105195e-11, ... % uc
                0.4044483,    ... % ags
                -2.730673e-3, ... % keta
                105,          ... % rdsw
                1,            ... % wr
                -3.773529e-9, ... % dwg
                5.239518e-9,  ... % dwb
                0,            ... % cit
                0,            ... % cdscb
                0.0167866,    ... % dsub
                3.38377e-3,   ... % pdiblc2
                8e10,         ... % pscbe1
                0.01,         ... % delta
                0,            ... % prt
                0,            ... % kt1l
                -7.61e-18,    ... % ub1
                0,            ... % wl
                1,            ... % wwn
                1,            ... % lln
                0,            ... % lwl
                7.9e-10,      ... % cgdo
                9.539798e-4,  ... % cj
                2.53972e-10,  ... % cjsw
                3.3e-10,      ... % cjswg
                0,            ... % cf
                -4.42044e-4,  ... % pk2
                10.8203648,   ... % pu0
                1.388017e3,   ... % pvsat
                4.1e-9,       ... % tox
                2.3549e17,    ... % nch
                1.63871e-3,   ... % k2
                1e-7,         ... % w0
                0,            ... % dvt1w
                0.3683763,    ... % dvt1
                -1.504141e-9, ... % ua
                9.896282e4,   ... % vsat
                -4.706134e-8, ... % b0
                5.916677e-4,  ... % a1
                0.5,          ... % prwg
                0,            ... % wint
                -0.0883818,   ... % voff
                2.4e-4,       ... % cdsc
                2.470369e-3,  ... % eta0
                0.7326932,    ... % pclm
                -0.1,         ... % pdiblcb
                1.254966e-9,  ... % pscbe2
                6.5,          ... % rsh
                -1.5,         ... % ute
                0.022,        ... % kt2
                -5.6e-11,     ... % uc1
                1,            ... % wln
                0,            ... % wwl
                0,            ... % lw
                2,            ... % capmod
                7.9e-10,      ... % cgso
                0.8,          ... % pb
                0.8,          ... % pbsw
                0.8,          ... % pbswg
                7.505753e-4,  ... % pvth0
                3.100384e-3,  ... % wketa
                2.896652e-11, ... % pua
                8.758549e-5,  ... % peta0
                0.3696986,    ... % vth0
                1e-3,         ... % k3
                1.71872e-7,   ... % nlx
                0,            ... % dvt2w
                0.0540199,    ... % dvt2
                2.428646e-18, ... % ub
                1.8904342,    ... % a0
                1.294942e-6,  ... % b1
                0.9069159,    ... % a2
                -0.2,         ... % prwb
                1.69494e-8,   ... % lint
                2.1821266,    ... % nfactor
                0,            ... % cdscd
                1.047744e-5,  ... % etab
                0.1823102,    ... % pdiblc1
                0.7469045,    ... % drout
                0,            ... % pvag
                1,            ... % mobmod
                -0.11,        ... % kt1
                4.31e-9,      ... % ua1
                3.3e4,        ... % at
                0,            ... % ww
                0,            ... % ll
                1,            ... % lwn
                0.5,          ... % xpart
                1e-12,        ... % cgbo
                0.380768,     ... % mj
                0.1061193,    ... % mjsw
                0.1061193,    ... % mjswg
                -2.7650517,   ... % prdsw
                -0.0104103,   ... % lketa
                1.684125e-23, ... % pub
                1.549791e-3,  ... % pketa
            };
        otherwise
            error(strcat('The value for TYPE(', Type, ')is invalid. See help set_MOSFET_parms for details.'));
            return;
    end

    % Apply the parameter values to the model
    MOD = MOD.setparms(parm_names, parm_vals, MOD);
end